package com.deuxhuithuit.ImageColorer.Core.My.Resources;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




//This class was auto-generated by the StronglyTypedResourceBuilder
//class via a tool like ResGen or Visual Studio.
//To add or remove a member, edit your .ResX file then rerun ResGen
//with the /str option, or rebuild your VS project.
/**
  A strongly-typed resource class, for looking up localized strings, etc.
*/
//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()>
public final class Resources
{

	private static System.Resources.ResourceManager resourceMan;

	private static System.Globalization.CultureInfo resourceCulture;

	/**
	  Returns the cached ResourceManager instance used by this class.
	*/
//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
	public static System.Resources.ResourceManager getResourceManager()
	{
		if (Object.ReferenceEquals(resourceMan, null))
		{
			System.Resources.ResourceManager temp = new System.Resources.ResourceManager("com.deuxhuithuit.ImageColorer.Core.Resources", Resources.class.getPackage());
			resourceMan = temp;
		}
		return resourceMan;
	}

	/**
	  Overrides the current thread's CurrentUICulture property for all
	  resource lookups using this strongly typed resource class.
	*/
//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
	public static System.Globalization.CultureInfo getCulture()
	{
		return resourceCulture;
	}
	public static void setCulture(System.Globalization.CultureInfo value)
	{
		resourceCulture = value;
	}
}