package com.deuxhuithuit.ImageColorer.Console.My;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//<System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"), System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
public final class MySettings extends System.Configuration.ApplicationSettingsBase
{
	private static MySettings defaultInstance = (MySettings)System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings());

//VB TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
///#Region "My.Settings Auto-Save Functionality"
//VB TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
//#if _MyType == "WindowsForms"
private static boolean addedHandler;

private static Object addedHandlerLockObject = new Object();

//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//<System.Diagnostics.DebuggerNonUserCodeAttribute(), System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>
private static void AutoSaveSettings(Object sender, System.EventArgs e)
{
	if (My.Application.SaveMySettingsOnExit)
	{
		My.Settings.Save();
	}
}
//#endif
//VB TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
///#End Region

	public static MySettings getDefault()
	{

//VB TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
//#if _MyType == "WindowsForms"
	   if (! addedHandler)
	   {
			synchronized (addedHandlerLockObject)
			{
				if (! addedHandler)
				{
//VB TO JAVA CONVERTER TODO TASK: Java has no equivalent to 'AddHandler':
//VB TO JAVA CONVERTER TODO TASK: Delegates are not available in Java:
					AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings;
					addedHandler = true;
				}
			}
		}
//#endif
		return defaultInstance;
	}
}