package com.deuxhuithuit.ImageColorer.Console.My.My;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------






//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//<Microsoft.VisualBasic.HideModuleNameAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	public final class MySettingsProperty
	{

//VB TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
		//<System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
		public static com.deuxhuithuit.ImageColorer.Console.My.MySettings getSettings()
		{
			return com.deuxhuithuit.ImageColorer.Console.My.MySettings.getDefault();
		}
	}